[project]
name = "scraper-amiami"
version = "0.1.0"
description = "AmiAmi scraper"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cffi>=1.15.1",
    "curl-cffi>=0.5.7",
    "pycparser>=2.21",
    "pydantic>=2.10.6",
]